steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/devops-451104/shoaib-100940517/server:${COMMIT_SHA}',
      '-f', 'Dockerfile',  # Explicitly reference the Dockerfile
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/devops-451104/shoaib-100940517/server:${COMMIT_SHA}']
